code/jalesa/grocery_list/grocery_app/urls.py
from django.urls import path
from . import views


app_name = 'grocery_app'
urlpatterns = [
    path('',views.index, name='index'),
    path('add/',views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

code/jalesa/grocery_list/grocery_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('grocery_app/', include('grocery_app.urls')),
]

code/jalesa/grocery_list/grocery_app/models.py
from django.db import models
from django.utils import timezone
import datetime


# This can be done with a single app called grocery_list and model called GroceryItem which contains a text description, a created date, a completed date, and a boolean representing whether it was completed.

# The user should be presented with an input field and a button (in a form). 
# When the clicks the button, it should save the data to the server and show the newly-added item in the list.
#  The user should be presented with a list of incomplete items and a list of complete items. 
# THe user should be able to mark an item complete/incomplete and be able to delete an item.


class Grocery_item(models.Model):
    grocery_item = models.CharField(max_length=200)
    description = models.TextField()
    pub_date = models.DateTimeField('date published')
    completed_date = models.DateTimeField('date completed', blank=True, null=True)
    is_completed= models.BooleanField(default=False)

    def __str__(self):
        return self.grocery_item # return a string representation of grocery_item
    
# create a form in Django
    # input_field
    # submit button












# 1. Remove all the migration files

# 2. Delete db.sqlite3
# rm db.sqlite3

# 3. Create and run the migrations:
# python manage.py makemigrations
# python manage.py migrate

# 4. Sync the database:
# python manage.py migrate --run-syncdb

code/jalesa/grocery_list/grocery_app/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from .models import Grocery_item
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# Create your views here.

'''views.py is how urls.py interact with this particular app'''

def index(request):
    context = {
        "incomplete_items": Grocery_item.objects.filter(is_completed= False),
        "complete_items": Grocery_item.objects.filter(is_completed = True)
    }
    return render(request, 'grocery_app/index.html', context)

def add(request):
    # this answer is generated from the input field in my form on index.html
    input_answer = request.POST['text_field']
    # its creating and adding whatever the user types in and adding it to the Grocery list and the time it was published
    Grocery_item.objects.create(grocery_item = input_answer, pub_date = timezone.now())
    # 
    return HttpResponseRedirect(reverse('grocery_app:index'))

def delete(request, grocery_id):
    grocery = get_object_or_404(Grocery_item, pk=grocery_id)
    grocery.delete()

    




# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     return render(request, 'polls/index.html', context)


# def detail(request, question_id):
#         question = get_object_or_404(Question, pk=question_id)
#         return render(request, 'polls/detail.html',{'question':question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

code/jalesa/grocery_list/grocery_app/templates/grocery_app/index.html
<!doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" />
        <link rel="stylesheet" href="home.css" />
        <meta charset="UTF-8">
        <meta name="author" content="Jalesa Peterson">
        <title> Home - Grocey List </title>
    </head>

    <body>
    {% comment %} # The user should be presented with an input field and a button (in a form). 
# When the clicks the button, it should save the data to the server and show the newly-added item in the list.
#  The user should be presented with a list of incomplete items and a list of complete items. 
{% comment %} # THe user should be able to mark an item complete/incomplete and be able to delete an item. {% endcomment %}

        <!-- ---------------------------    FORM    --------------------------------------- -->
                 <!--------------    INPUT FIELD & SAVE BUTTON -------->
        <h1>GROCERY LIST DATABASE<h1>
        <p> incomplete items </p>
        {%for item in incomplete_items%}
            <ul>
                <li>{{item}}</li>
                <input type="radio" id="complete" value="complete" name="items"> </input>
                <label for="complete">complete</label>
                <input type="radio" id="incomplete" value="incomplete" name="items"></input>
                <label for="incomplete">incomplete</label>
                <input id="delete" type="radio"  name="items"> </input>
                <label for="delete"> Delete</label>
            </ul>
        {% endfor %}
        

        <p> complete items </p>
        {%for item in complete_items%}
            <ul>
                <li>{{item}}</li>
                <input type="radio" id="complete" value="complete" name="items"> </input>
                <label for="complete">complete</label>
                <input type="radio" id="incomplete" value="incomplete" name="items"></input>
                <label for="incomplete">incomplete</label>
                <input action="{% url 'grocery_app:delete' %}" method="post" id="delete" type="radio"  name="items"> </input>
                <label for="delete"> Delete</label>
            </ul>
        {% endfor %}
        <form action="{% url 'grocery_app:add' %}" method="post">
            {% comment %} csrf_token is encripting all of my data in the url {% endcomment %}
            {% csrf_token %} 
            <label for="text_field">New Item:</label>
            <input id="text_field" name="text_field" type="text">
            <br>
            {% comment %} how is save button saving data to the database {% endcomment %}
            <input type="submit" class="save_button" value="Save"></input>
         </form>
    </body>
</html>