3 Django/solutions/groceryproj/groceryapp/urls.py
from django.urls import path

from . import views

app_name = 'groceryapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:grocery_list_id>/', views.detail, name='detail'),
    path('<int:grocery_list_id>/additem', views.additem, name='additem'),
    path('<int:grocery_list_id>/applycoupon', views.applycoupon, name='applycoupon')
]

3 Django/solutions/groceryproj/groceryproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('groceryapp.urls'))
]

handler404 = 'groceryapp.views.handler404'
handler500 = 'groceryapp.views.handler500'

3 Django/solutions/groceryproj/groceryapp/models.py
from django.db import models


class Coupon(models.Model):
    name = models.CharField(max_length=100)
    percent_off = models.FloatField()

    def __str__(self):
        return self.name


class GroceryItem(models.Model):
    name = models.CharField(max_length=100)
    unit_price = models.FloatField()

    def __str__(self):
        return self.name

    def pretty_unit_price(self):
        return '{0:.2f}'.format(self.unit_price)

class GroceryList(models.Model):
    name = models.CharField(max_length=100)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_total_sans_coupon(self):
        total = 0.0
        for grocery_list_item in self.grocerylistitem_set.all():
            total += grocery_list_item.quantity * grocery_list_item.grocery_item.unit_price
        return '{0:.2f}'.format(total)

    def get_total(self):
        total = 0.0
        for grocery_list_item in self.grocerylistitem_set.all():
            total += grocery_list_item.quantity * grocery_list_item.grocery_item.unit_price

        # coupon_percent = 0 if self.coupons.count() == 0 else self.coupons.all()[0].percent_off
        coupon_percent = 0 if self.coupon is None else self.coupon.percent_off

        return '{0:.2f}'.format(total*(1.0-coupon_percent/100.0)) + ' (' + str(coupon_percent) + '% off)'



class GroceryListItem(models.Model):
    grocery_item = models.ForeignKey(GroceryItem, on_delete=models.CASCADE)
    grocery_list = models.ForeignKey(GroceryList, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.grocery_list.name + ' - ' + self.grocery_item.name

3 Django/solutions/groceryproj/groceryapp/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse, HttpResponseRedirect

from .models import Coupon, GroceryItem, GroceryList, GroceryListItem


def index(request):
    grocery_lists = GroceryList.objects.order_by('name')
    return render(request, 'groceryapp/index.html', {'grocery_lists': grocery_lists})


def detail(request, grocery_list_id):
    # grocery_list = GroceryList.objects.get(pk=grocery_list_id)
    grocery_list = get_object_or_404(GroceryList, pk=grocery_list_id)
    grocery_items = GroceryItem.objects.order_by('name')
    coupons = Coupon.objects.order_by('name')
    context = {'grocery_list': grocery_list, 'grocery_items': grocery_items, 'coupons':coupons}
    return render(request, 'groceryapp/detail.html', context)



def additem(request, grocery_list_id):
    grocery_list = GroceryList.objects.get(pk=grocery_list_id)
    grocery_item_id = request.POST['grocery_item_id']
    quantity = request.POST['quantity']
    grocery_item = GroceryItem.objects.get(pk=grocery_item_id)

    grocery_list_item = grocery_list.grocerylistitem_set.filter(grocery_item_id=grocery_item_id).first()
    if grocery_list_item is None:
        grocery_list_item = GroceryListItem(grocery_list=grocery_list, grocery_item=grocery_item, quantity=quantity)
        grocery_list_item.save()
    else:
        grocery_list_item.quantity += int(quantity)
        grocery_list_item.save()

    return HttpResponseRedirect(reverse('groceryapp:detail', kwargs={'grocery_list_id':grocery_list_id}))



def applycoupon(request, grocery_list_id):
    grocery_list = GroceryList.objects.get(pk=grocery_list_id)
    coupon_id = request.POST['coupon_id']
    if coupon_id == 'null':
        grocery_list.coupon = None
    else:
        grocery_list.coupon_id = coupon_id
    grocery_list.save()

    return HttpResponseRedirect(reverse('groceryapp:detail', kwargs={'grocery_list_id':grocery_list_id}))




def handler404(request):
    return HttpResponseRedirect('https://http.cat/404')


def handler500(request):
    return HttpResponseRedirect('https://http.cat/500')

3 Django/solutions/groceryproj/groceryapp/templates/groceryapp/detail.html
<h1>{{grocery_list.name}}</h1>


<form action="{% url 'groceryapp:additem' grocery_list.id %}" method="post">
    {% csrf_token %}
    <select name="grocery_item_id">
        {% for grocery_item in grocery_items %}
        <option value="{{grocery_item.id}}">{{grocery_item.name}} - ${{grocery_item.pretty_unit_price}}</option>
        {% endfor %}
    </select>
    <input name="quantity" type="number" value="1"/>
    <button type="submit">add</button>
</form>

<hr/>

<form action="{% url 'groceryapp:applycoupon' grocery_list.id %}" method="post">
    {% csrf_token %}
    <select name="coupon_id">
        <option value="null">-----------</option>
        {% for coupon in coupons %}
        <option value="{{coupon.id}}">{{coupon.name}} ({{coupon.percent_off}}% off)</option>
        {% endfor %}
    </select>
    <button type="submit">apply</button>
</form>

<hr/>

<table>
    <tr>
        <th>Item</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>
    {% for grocery_list_item in grocery_list.grocerylistitem_set.all %}
    <tr>
        <td>{{grocery_list_item.grocery_item.name}}</td>
        <td>{{grocery_list_item.quantity}}</td>
        <td>{{grocery_list_item.grocery_item.pretty_unit_price}}</td>
    </tr>
    {% endfor %}
</table>
<div>total sans coupon: {{grocery_list.get_total_sans_coupon}}</div>
<div>total: {{grocery_list.get_total}}</div>

3 Django/solutions/groceryproj/groceryapp/templates/groceryapp/index.html
<ul>
{% for grocery_list in grocery_lists %}
    <li>
        <a href="{% url 'groceryapp:detail' grocery_list.id %}">{{grocery_list.name}}</a>
    </li>
{% endfor %}
</ul>